import Link from "next/link";

import { Mark } from "./Nav";

const COLUMNS: { title: string; links: { label: string; href: string }[] }[] = [
  {
    title: "The loop",
    links: [
      { label: "Attack Atlas", href: "/atlas" },
      { label: "Simulation Studio", href: "/studio" },
      { label: "Defense Console", href: "/defense" },
      { label: "Red vs Blue Arena", href: "/arena" },
      { label: "Live Console", href: "/console" },
    ],
  },
  {
    title: "Pillars",
    links: [
      { label: "Identify — 42 vectors", href: "/atlas" },
      { label: "Generate — 14 injectors", href: "/studio" },
      { label: "Defend — 4 channels", href: "/defense" },
      { label: "Co-evolve — Time-to-Immunity", href: "/arena" },
    ],
  },
  {
    title: "Evidence",
    links: [
      { label: "Zero-day holdout", href: "/defense#zero-day" },
      { label: "Channel ablations", href: "/defense#ablations" },
      { label: "False positives", href: "/defense#false-positives" },
      { label: "Reason codes", href: "/console" },
      { label: "Case files", href: "/console#cases" },
    ],
  },
];

export default function Footer() {
  return (
    <footer className="mt-24 border-t border-line">
      <div className="mx-auto w-full max-w-[1320px] px-4 py-14 sm:px-6 lg:px-8">
        <div className="grid gap-10 md:grid-cols-[1.4fr_1fr_1fr_1fr]">
          <div>
            <div className="flex items-center gap-2.5">
              <Mark className="h-[22px] w-[22px] text-mint" />
              <span className="mono text-[15px] font-semibold tracking-tight">
                IMMUNIS
                <sup className="ml-0.5 text-[9px] font-normal text-fg-faint">TM</sup>
              </span>
            </div>
            <p className="mt-3 max-w-[260px] text-[13px] leading-relaxed text-fg-muted">
              An adversarial immune system for payment networks. We manufacture
              the fraud that hasn&apos;t happened yet, so the model already knows it.
            </p>
            <p className="mono mt-5 text-[11px] leading-relaxed text-fg-faint">
              Mastercard Innovation Challenge 2026
              <br />
              AI Defense Lab for Payment Security
            </p>
          </div>

          {COLUMNS.map((col) => (
            <div key={col.title}>
              <div className="mono mb-3 text-[13px] font-medium text-fg">
                {col.title}
              </div>
              <ul className="space-y-2">
                {col.links.map((l) => (
                  <li key={l.label}>
                    <Link
                      href={l.href}
                      className="text-[13px] text-fg-muted transition-colors hover:text-fg"
                    >
                      {l.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>

      <div className="border-t border-line">
        <div className="mx-auto flex w-full max-w-[1320px] flex-wrap items-center justify-between gap-3 px-4 py-5 sm:px-6 lg:px-8">
          <p className="text-[12px] text-fg-faint">
            Every figure on this site is generated by the engine in{" "}
            <code className="mono text-fg-muted">engine/</code>. Nothing is
            hand-entered.
          </p>
          <p className="mono text-[11px] text-fg-faint">
            All entities, transactions and conversations are synthetic. No real
            cardholder data is used anywhere.
          </p>
        </div>
      </div>
    </footer>
  );
}
