"""Generate docs/RESULTS.md and docs/ATTACK_ATLAS.md from the artefacts.

Written numbers drift. Generated ones do not — so the two documents that quote
figures are produced from the same JSON the web prototype reads.

    python scripts/make_docs.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

ROOT = Path(__file__).resolve().parent.parent
ART = ROOT / "artifacts"
DOCS = ROOT / "docs"


def load(name: str):
    path = ART / name
    if not path.exists():
        sys.exit(f"missing {path} — run `python -m immunis.cli run` first")
    return json.loads(path.read_text(encoding="utf-8"))


def pct(x, d=1):
    return "—" if x is None else f"{x * 100:.{d}f}%"


def num(x):
    return "—" if x is None else f"{x:,}"


def inr(x):
    if x is None:
        return "—"
    if abs(x) >= 1e7:
        return f"Rs {x / 1e7:.2f} Cr"
    if abs(x) >= 1e5:
        return f"Rs {x / 1e5:.2f} L"
    return f"Rs {x:,.0f}"


SHORT = {
    "AV-DIGITAL-ARREST": "Coercion-authorised payment (digital arrest)",
    "AV-VOICE-CLONE": "Cloned-voice distress / executive request",
    "AV-AITM-OTP": "Adversary-in-the-middle OTP relay",
    "AV-BIO-CLONE": "Behavioural-biometric cloning",
    "AV-SYNTH-ID": "Synthetic identity bust-out",
    "AV-DEEPFAKE-KYC": "Deepfake KYC onboarding to mule cash-out",
    "AV-BIN-ENUM": "BIN enumeration / card testing",
    "AV-QR-SWAP": "QR tampering / collect-request abuse",
    "AV-TOKEN-PROV": "Wallet token provisioning fraud",
    "AV-FAKE-MERCH": "Synthetic merchant / transaction laundering",
    "AV-FRIENDLY-FRAUD": "First-party misuse / generated disputes",
    "AV-MULE-LAYER": "Fan-in / fan-out mule layering",
    "AV-AGENT-INJECT": "Prompt-injected shopping agent",
    "AV-AGENT-MANDATE": "Over-scoped agent payment mandate",
}


# ---------------------------------------------------------------------------

def results_md(run, sim, det, arena) -> str:
    base, post = det["baseline"], det["post_arena"]
    op, bop = post["operating_point"], base["operating_point"]
    gens = arena["generations"] if arena else []
    L: list[str] = []
    a = L.append

    a("# Results\n")
    a("> Generated by `scripts/make_docs.py` from `artifacts/`. "
      f"Run `{run['profile']}` profile, seed `{run['seed']}`, "
      f"Python {run['environment']['python']}, {run['total_seconds']}s end to end.\n")
    a("Every figure below is computed on a **temporal** holdout — the model is "
      "always evaluated on transactions that occur after everything it was "
      "trained on — and against **ground-truth** labels, even though the model "
      "was trained on deliberately corrupted ones.\n")

    a("\n## Headline\n")
    a("| Metric | Before the arena | After the arena |")
    a("|---|---|---|")
    a(f"| ROC-AUC | {base['roc_auc']:.4f} | **{post['roc_auc']:.4f}** |")
    a(f"| PR-AUC | {base['pr_auc']:.4f} | **{post['pr_auc']:.4f}** |")
    a(f"| Recall @ {pct(op['alert_rate'])} alert budget | {pct(bop['recall'])} | **{pct(op['recall'])}** |")
    a(f"| False-positive rate | {pct(bop['fpr'], 3)} | **{pct(op['fpr'], 3)}** |")
    a(f"| Value recall | {pct(bop['value_recall'])} | **{pct(op['value_recall'])}** |")
    a(f"| Brier score | {base['brier']:.5f} | **{post['brier']:.5f}** |")
    a("")
    a(f"Test slice: {num(post['n_test'])} transactions, {num(post['n_test_fraud'])} "
      f"fraudulent ({pct(post['test_fraud_rate'], 2)}).\n")

    a("### Precision, reported twice\n")
    a(f"- In simulation, at {pct(post['test_fraud_rate'], 2)} prevalence: "
      f"**{pct(op['precision'])}**")
    a(f"- Bayes-adjusted to {pct(det['realistic_prevalence'], 2)} — the prevalence a "
      f"real portfolio runs at: **{pct(op['precision_at_real_prevalence'])}** "
      f"(~{round(1 / max(0.001, op['precision_at_real_prevalence']))} alerts reviewed "
      "per fraud found)\n")
    a("The second number is the one an operations team should staff against. "
      "Quoting only the first would be flattering and useless.\n")

    a("\n## Recall by typology\n")
    a("At one shared operating threshold. An average hides the family you are blind to.\n")
    a("| Typology | n | Recall | Value recall | Median score | Held out |")
    a("|---|---:|---:|---:|---:|:--:|")
    for vid, d in sorted(post["per_vector"].items(), key=lambda kv: kv[1]["recall"]):
        a(f"| {SHORT.get(vid, vid)} | {d['n']} | {pct(d['recall'])} | "
          f"{pct(d['value_recall'])} | {d['median_score']:.3f} | "
          f"{'yes' if d['zero_day'] else ''} |")

    a("\n## False positives, by what kind of legitimate the transaction was\n")
    a("This is the table most synthetic-fraud demos leave out. "
      f"{pct(sim['summary']['benign_anomaly_rate'])} of legitimate traffic in the "
      "simulation is deliberately anomalous — genuine travel, real big-ticket "
      "purchases, device upgrades, first payments to a new payee. A low overall "
      "false-positive rate is easy if your legitimate traffic is boring.\n")
    fp = post["false_positives_by_benign_anomaly"]
    baseline_fpr = fp.get("__normal__", {}).get("false_positive_rate", 0) or 1e-9
    a("| Legitimate behaviour | n | False-positive rate | vs ordinary traffic |")
    a("|---|---:|---:|---:|")
    for k, d in sorted(fp.items(), key=lambda kv: -kv[1]["false_positive_rate"]):
        label = "Ordinary legitimate traffic" if k == "__normal__" else k.replace("_", " ")
        mult = "—" if k == "__normal__" else f"{d['false_positive_rate'] / baseline_fpr:.1f}x"
        a(f"| {label} | {num(d['n'])} | {pct(d['false_positive_rate'], 2)} | {mult} |")
    a("\nResidual errors concentrate on genuine big-ticket purchases — exactly "
      "where a real issuer's do.\n")

    a("\n## Zero-day holdout\n")
    zj = det.get("zero_day_journey", {})
    a("Two attack families were removed from training entirely.\n")
    a("| Held-out family | Cold start | After the arena | Lift |")
    a("|---|---:|---:|---:|")
    for f in zj.get("holdout_families", []):
        b = zj["before"].get(f)
        af = zj["after"].get(f)
        lift = "—" if (b is None or af is None) else f"{(af - b) * 100:+.1f} pt"
        a(f"| {SHORT.get(f, f)} | {pct(b)} | {pct(af)} | {lift} |")
    a("")
    a(zj.get("explanation", ""))
    a("")

    nov = det.get("novelty_profile", {})
    if nov:
        a("\n### Where each family sits versus the legitimate manifold\n")
        a(f"Legitimate traffic reaches the 99th novelty percentile at "
          f"{nov['legit_p99']:.4f}.\n")
        a("| Typology | Mean novelty percentile | Share above legit p99 | Held out |")
        a("|---|---:|---:|:--:|")
        for vid, d in sorted(nov["by_family"].items(),
                             key=lambda kv: -kv[1]["mean_novelty_percentile"]):
            a(f"| {SHORT.get(vid, vid)} | {d['mean_novelty_percentile']:.3f} | "
              f"{pct(d['share_above_legit_p99'], 0)} | "
              f"{'yes' if d['zero_day'] else ''} |")
        a("\nThe split result is the honest one: one held-out family sits far "
          "outside the legitimate manifold and the unsupervised channel sees it "
          "coming; the other is engineered to look normal and it does not.\n")

    a("\n## What each channel is worth\n")
    a("Each row is a model retrained from scratch with that channel's features removed.\n")
    a("| Channel removed | Features dropped | ROC-AUC | PR-AUC | Delta PR-AUC | Recall | Delta recall |")
    a("|---|---:|---:|---:|---:|---:|---:|")
    a(f"| nothing (full model) | 0 | {base['roc_auc']:.4f} | {base['pr_auc']:.4f} | — | "
      f"{pct(bop['recall'])} | — |")
    for tag, ab in det["ablations"].items():
        a(f"| {tag.replace('no_', '')} | {len(ab['dropped_features'])} | "
          f"{ab['roc_auc']:.4f} | {ab['pr_auc']:.4f} | {ab['delta_pr_auc']:+.4f} | "
          f"{pct(ab['recall'])} | {ab['delta_recall'] * 100:+.1f} pt |")

    stress = det.get("narrative_stress_test") or {}
    if stress.get("sweep"):
        a("\n### A negative result we are keeping\n")
        a("Our thesis was that reading the pre-transaction conversation would "
          "catch coercion payments the transaction side cannot see. The ablation "
          "says otherwise, so we built the experiment that could have rescued it: "
          "a high-mimicry operator (aged mule beneficiaries, amounts shaped under "
          "step-up thresholds, the victim taken off screen share before "
          "authorising) swept across how greedy they are.\n")
        a("| Aggression | n | Mean amount | Amount z | With narrative | Without | Lift |")
        a("|---:|---:|---:|---:|---:|---:|---:|")
        for p in stress["sweep"]:
            a(f"| {p['aggression']:.2f} | {p['n']} | {inr(p['mean_amount'])} | "
              f"{p['mean_amount_z']:+.2f} | {pct(p['recall_full'])} | "
              f"{pct(p['recall_without_narrative'])} | {p['lift']:+.3f} |")
        a("\nThe lift is zero at every point. Beneficiary novelty and account age "
          "already carry this typology in our simulation. We would still ship the "
          "channel — a coercion alert an analyst can justify to a regulator is "
          "worth more than one they cannot, and it is the only signal left when "
          "session telemetry is missing — but it is a design bet, not a measured "
          "win, and we label it that way.\n")

    if gens:
        a("\n## The arena\n")
        tti = arena["time_to_immunity_generations"]
        a(f"**Time-to-Immunity: {tti if tti else 'not reached'} generation(s)** — "
          f"the first generation at which post-retrain evasion fell below "
          f"{pct(arena['immunity_threshold'], 0)} with the false-positive budget "
          f"intact. Wall clock for the whole loop: {arena['wall_seconds']}s.\n")
        a("| Gen | Strains | Attacks | Evasion found | Evasion after retrain | Mined | Blue AUC | Recall | FPR | Budget |")
        a("|---:|---:|---:|---:|---:|---:|---:|---:|---:|:--:|")
        for g in gens:
            a(f"| {g['generation']} | {g['population']} | {num(g['attack_rows'])} | "
              f"{pct(g['evasion_pre'], 2)} | {pct(g['evasion_post'], 2)} | {g['mined']} | "
              f"{g['blue_after']['auc']:.4f} | {pct(g['blue_after']['recall'], 2)} | "
              f"{pct(g['blue_after']['fpr'], 3)} | "
              f"{'ok' if g['fpr_within_budget'] else 'BREACH'} |")
        d = arena["delta"]
        a(f"\nAcross the run the blue model gained {d['recall'] * 100:+.1f} points of "
          f"recall and {d['value_recall'] * 100:+.1f} points of value recall, while "
          f"its false-positive rate moved {d['fpr'] * 100:+.3f} points — against a "
          f"ceiling of {pct(arena['fpr_budget_ceiling'], 2)} it was not allowed to "
          f"exceed. {num(gens[-1]['mined_cumulative'])} evading transactions were "
          "mined and folded back into training.\n")

    a("\n## Simulation fidelity\n")
    s = sim["summary"]
    rows = [
        ("Transactions", num(s["transactions"])),
        ("Fraudulent", f"{num(s['fraud_transactions'])} ({pct(s['fraud_rate'], 2)})"),
        ("Total value", inr(s["total_value"])),
        ("Fraudulent value share", pct(s["fraud_value_share"])),
        ("Customers / merchants", f"{num(run['generate']['customers'])} / {num(run['generate']['merchants'])}"),
        ("Days simulated", str(s["days"])),
        ("Conversations", f"{num(s['episodes'])} ({num(s['fraud_episodes'])} scam)"),
        ("Mule-graph edges", num(s["graph_edges"])),
        ("Benign anomaly rate", pct(s["benign_anomaly_rate"])),
        ("Session telemetry coverage", pct(s["telemetry_coverage"], 0)),
        ("Training fraud hidden by label noise", num(sim["label_noise"]["training_frauds_hidden"])),
        ("Cover traffic from mule identities", num(s["cover_transactions"])),
        ("Causal features", str(sim["feature_count"])),
        ("Split", f"{sim['split']['split']} — {num(sim['split']['train_rows'])} train / "
                  f"{num(sim['split']['calib_rows'])} calibrate / {num(sim['split']['test_rows'])} test"),
    ]
    a("| | |")
    a("|---|---|")
    for k, v in rows:
        a(f"| {k} | {v} |")

    a("\n## Economics at the operating point\n")
    cm = det["cost_model"]
    a(f"Cost model: Rs {cm['review_cost']:.0f} per analyst review, "
      f"Rs {cm['false_decline_cost']:.0f} per false decline, "
      f"{pct(cm['fraud_loss_ratio'], 0)} of a missed fraud's value borne by the "
      f"network, {pct(cm['decline_share'], 0)} of alerts hard-declined rather than "
      "stepped up.\n")
    co = post["cost_optimal_point"]
    a("| | Review-budget point | Cost-optimal point |")
    a("|---|---:|---:|")
    a(f"| Threshold | {op['threshold']:.4f} | {co['threshold']:.4f} |")
    a(f"| Recall | {pct(op['recall'])} | {pct(co['recall'])} |")
    a(f"| Precision | {pct(op['precision'])} | {pct(co['precision'])} |")
    a(f"| Alert rate | {pct(op['alert_rate'], 2)} | {pct(co['alert_rate'], 2)} |")
    a(f"| Value stopped | {inr(op['value_caught'])} | {inr(co['value_caught'])} |")
    a(f"| Expected cost | {inr(op['expected_cost'])} | {inr(co['expected_cost'])} |")

    a("\n## Reproducing\n")
    a("```bash\ncd engine\npython -m immunis.cli run --profile "
      f"{run['profile']} --seed {run['seed']}\npython scripts/make_docs.py\n```\n")
    return "\n".join(L) + "\n"


def atlas_md(atlas) -> str:
    L: list[str] = []
    a = L.append
    st = atlas["stats"]
    a("# The Attack Atlas\n")
    a("> Generated by `scripts/make_docs.py` from `artifacts/atlas.json`.\n")
    a(f"**{st['total_vectors']} curated vectors** across {st['families']} families, "
      f"{len(st['by_rail'])} payment rails and {len(st['by_surface'])} attack "
      f"surfaces, plus **{atlas['discovered']} machine-composed hybrids**. "
      f"{st['simulated_vectors']} have a working generator in this repository.\n")
    a("Scope note: entries describe observable behaviour and telemetry "
      "signatures — what a defender can model. They deliberately contain no "
      "operational playbooks, tooling or infrastructure. See "
      "`docs/RESPONSIBLE_USE.md`.\n")

    a("\n## Threat scoring\n")
    a("```\n0.30 x detection_gap + 0.24 x genai_uplift + 0.20 x impact\n"
      "  + 0.15 x scale_velocity + 0.11 x feasibility\n```\n")
    a("Weighted so that *what we cannot currently see* dominates: a cheap, "
      "scalable attack the incumbent stack misses deserves more red-team "
      "attention than an expensive one it already catches.\n")

    a("\n## Coverage\n")
    a("| Dimension | Breakdown |")
    a("|---|---|")
    for key, label in (("by_family", "Family"), ("by_surface", "Surface"),
                       ("by_rail", "Rail"), ("by_priority", "Priority")):
        parts = ", ".join(f"{k} ({v})" for k, v in
                          sorted(st[key].items(), key=lambda kv: -kv[1]))
        a(f"| {label} | {parts} |")

    a("\n## Ranked\n")
    a("| ID | Threat | Priority | Name | Rails | Status |")
    a("|---|---:|---|---|---|---|")
    for v in sorted(atlas["vectors"], key=lambda x: -x["threat_score"]):
        a(f"| `{v['id']}` | {v['threat_score']} | {v['priority']} | {v['name']} | "
          f"{', '.join(v['rails'])} | {v['status']} |")

    a("\n## Simulated vectors, in detail\n")
    for v in sorted([x for x in atlas["vectors"] if x["status"] == "simulated"],
                    key=lambda x: -x["threat_score"]):
        a(f"\n### {v['id']} — {v['name']}\n")
        a(f"**Family** {v['family']} · **Surface** {v['surface']} · "
          f"**Rails** {', '.join(v['rails'])} · **Threat** {v['threat_score']} "
          f"({v['priority']})\n")
        a(v["summary"] + "\n")
        a(f"**Why GenAI changes it.** {v['uplift_note']}\n")
        a("**Kill chain**\n")
        for i, k in enumerate(v["kill_chain"], 1):
            a(f"{i}. {k}")
        a("\n**Observable signals**\n")
        for s in v["observable_signals"]:
            a(f"- {s}")
        a("\n**Mitigations**\n")
        for m in v["mitigations"]:
            a(f"- {m}")
        a(f"\n**Historical analogue** {v['historical_analogue']}  ")
        a(f"**Who it hits** {v['victim_profile']}  ")
        a(f"**Generator** `engine/immunis/generate/attacks/` → `{v['injector']}`")
        if v.get("notes"):
            a(f"  \n**Note** {v['notes']}")
        a("")

    a("\n## Discovered composites\n")
    a("The discovery agent chains atlas vectors where one stage's output "
      "capability satisfies the next stage's precondition, and rewards "
      "composites that straddle *observability boundaries* — the seams where "
      "each half looks unremarkable to the system that sees it, and no single "
      "institution sees the whole.\n")
    for v in [x for x in atlas["vectors"] if x["status"] == "discovered"]:
        a(f"\n### {v['id']} — {v['name']}\n")
        a(f"**Composed from** `{'` + `'.join(v['parents'])}` · "
          f"**Threat** {v['threat_score']} ({v['priority']})\n")
        a(v["summary"] + "\n")
    return "\n".join(L) + "\n"


def main() -> None:
    import walkthrough

    run, sim, det = load("run.json"), load("simulation.json"), load("detection.json")
    atlas = load("atlas.json")
    arena = json.loads((ART / "arena.json").read_text(encoding="utf-8")) \
        if (ART / "arena.json").exists() else None

    DOCS.mkdir(exist_ok=True)
    (DOCS / "RESULTS.md").write_text(results_md(run, sim, det, arena), encoding="utf-8")
    (DOCS / "ATTACK_ATLAS.md").write_text(atlas_md(atlas), encoding="utf-8")
    (DOCS / "SOLUTION_WALKTHROUGH.md").write_text(
        walkthrough.build(run, sim, det, arena, atlas, pct=pct, num=num, inr=inr),
        encoding="utf-8")
    print(f"wrote {DOCS / 'RESULTS.md'}")
    print(f"wrote {DOCS / 'ATTACK_ATLAS.md'}")
    print(f"wrote {DOCS / 'SOLUTION_WALKTHROUGH.md'}")


if __name__ == "__main__":
    main()
